### PR TITLE
Proper node env var passing

### PR DESCRIPTION
**Pull request by tareq89**
Thanks for this awesome code example. It kinda saved my day, however I noticed that, the way it was written to pass env variable into node program was not working. I fixed it and creating this pull request. Hope you will consider it.  Have a good day :)

### CODE REVIEW

**Comment by camjackson** [comment]
Hi @tareq89, glad it was useful!

You're right that we were missing an `=` in the docs there. Is there a reason you removed the quotes around the values though?

**Comment by tareq89** [comment]
You are right, there is no reason apparently to remove the quotes. I missed them. Added them in another commit! :)

**Comment by camjackson** [comment]
Thanks very much, it's important that our docs are correct!

Do you mind if I ask what you're using this library for, and how you came across it?

**Comment by tareq89** [comment]
I had a development challenge from one of my friend, the challenge required the use of local kinesis stream usage with the serverless offline plugin. [here](https://github.com/tareq89/serverless-demo) is the repo of the project that I have done.

I basically searched Github anything related to kinesis and lambda, this way found yours :)

**Pull request merged**
